import type { Category, Product } from "./types";

export const categories: Category[] = [
  {
    id: "cat-kanjivaram-silk",
    slug: "kanjivaram-silk",
    name: "Kanjivaram Silk",
    description: "Temple-border silk sarees woven in Kanchipuram, rich with zari work.",
  },
  {
    id: "cat-banarasi-silk",
    slug: "banarasi-silk",
    name: "Banarasi Silk",
    description: "Brocade sarees from Varanasi featuring intricate gold and silver zari.",
  },
  {
    id: "cat-mysore-silk",
    slug: "mysore-silk",
    name: "Mysore Silk",
    description: "Lightweight pure silk sarees known for their soft sheen and drape.",
  },
  {
    id: "cat-cotton-sarees",
    slug: "cotton-sarees",
    name: "Cotton Sarees",
    description: "Breathable handloom cotton, perfect for everyday elegance.",
  },
  {
    id: "cat-chiffon-georgette",
    slug: "chiffon-georgette",
    name: "Chiffon & Georgette",
    description: "Flowing, lightweight sarees for parties and evening occasions.",
  },
  {
    id: "cat-bridal-collection",
    slug: "bridal-collection",
    name: "Bridal Collection",
    description: "Statement pieces for weddings and special occasions.",
  },
];

// NOTE: These are placeholder products so the store has something to show
// before real product photos and details are added. Replace or edit these
// from the Admin panel, or re-seed src/lib/seed-data.ts directly.
export const seedProducts: Product[] = [
  {
    id: "p-001",
    slug: "royal-maroon-kanjivaram",
    name: "Royal Maroon Kanjivaram",
    category: "kanjivaram-silk",
    price: 12999,
    compareAtPrice: 15999,
    description:
      "A classic maroon Kanjivaram silk saree with a wide gold zari temple border and contrast pallu. Woven by master weavers in Kanchipuram.",
    fabric: "Pure Mulberry Silk",
    color: "Maroon & Gold",
    stock: 6,
    featured: true,
    createdAt: "2026-01-05T10:00:00.000Z",
  },
  {
    id: "p-002",
    slug: "emerald-green-kanjivaram",
    name: "Emerald Green Kanjivaram",
    category: "kanjivaram-silk",
    price: 13499,
    compareAtPrice: null,
    description:
      "Deep emerald green Kanjivaram with a checkered pallu and traditional peacock motifs in zari.",
    fabric: "Pure Mulberry Silk",
    color: "Emerald Green",
    stock: 4,
    featured: true,
    createdAt: "2026-01-06T10:00:00.000Z",
  },
  {
    id: "p-003",
    slug: "mustard-yellow-kanjivaram",
    name: "Mustard Yellow Kanjivaram",
    category: "kanjivaram-silk",
    price: 11999,
    compareAtPrice: 13999,
    description:
      "Bright mustard yellow saree with a maroon temple border, ideal for festive occasions.",
    fabric: "Pure Mulberry Silk",
    color: "Mustard Yellow",
    stock: 5,
    createdAt: "2026-01-07T10:00:00.000Z",
  },
  {
    id: "p-004",
    slug: "royal-blue-kanjivaram",
    name: "Royal Blue Kanjivaram",
    category: "kanjivaram-silk",
    price: 14499,
    compareAtPrice: null,
    description:
      "Rich royal blue Kanjivaram with a contrasting coral pallu and gold zari border.",
    fabric: "Pure Mulberry Silk",
    color: "Royal Blue",
    stock: 3,
    createdAt: "2026-01-08T10:00:00.000Z",
  },
  {
    id: "p-005",
    slug: "banarasi-rani-pink",
    name: "Banarasi Rani Pink",
    category: "banarasi-silk",
    price: 9999,
    compareAtPrice: 11999,
    description:
      "Rani pink Banarasi silk saree with an all-over gold butta weave and heavy zari pallu.",
    fabric: "Banarasi Katan Silk",
    color: "Rani Pink",
    stock: 7,
    featured: true,
    createdAt: "2026-01-09T10:00:00.000Z",
  },
  {
    id: "p-006",
    slug: "banarasi-ivory-gold",
    name: "Banarasi Ivory & Gold",
    category: "banarasi-silk",
    price: 10999,
    compareAtPrice: null,
    description:
      "Elegant ivory Banarasi saree with dense gold zari brocade, perfect for receptions.",
    fabric: "Banarasi Katan Silk",
    color: "Ivory & Gold",
    stock: 5,
    createdAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "p-007",
    slug: "banarasi-wine-red",
    name: "Banarasi Wine Red",
    category: "banarasi-silk",
    price: 10499,
    compareAtPrice: 12499,
    description:
      "Wine red Banarasi silk with a jaal pattern and a richly woven gold pallu.",
    fabric: "Banarasi Katan Silk",
    color: "Wine Red",
    stock: 4,
    createdAt: "2026-01-11T10:00:00.000Z",
  },
  {
    id: "p-008",
    slug: "banarasi-peacock-teal",
    name: "Banarasi Peacock Teal",
    category: "banarasi-silk",
    price: 10999,
    compareAtPrice: null,
    description:
      "Peacock teal Banarasi saree with a contrasting magenta border and floral motifs.",
    fabric: "Banarasi Katan Silk",
    color: "Peacock Teal",
    stock: 6,
    createdAt: "2026-01-12T10:00:00.000Z",
  },
  {
    id: "p-009",
    slug: "mysore-silk-classic-purple",
    name: "Mysore Silk Classic Purple",
    category: "mysore-silk",
    price: 6999,
    compareAtPrice: 7999,
    description:
      "Lightweight pure Mysore silk in a deep purple with a slim gold border — easy to drape and carry all day.",
    fabric: "Pure Mysore Silk",
    color: "Purple",
    stock: 8,
    featured: true,
    createdAt: "2026-01-13T10:00:00.000Z",
  },
  {
    id: "p-010",
    slug: "mysore-silk-sunset-orange",
    name: "Mysore Silk Sunset Orange",
    category: "mysore-silk",
    price: 7299,
    compareAtPrice: null,
    description:
      "Sunset orange Mysore silk saree, soft and glossy with a simple zari border.",
    fabric: "Pure Mysore Silk",
    color: "Sunset Orange",
    stock: 5,
    createdAt: "2026-01-14T10:00:00.000Z",
  },
  {
    id: "p-011",
    slug: "mysore-silk-teal-blue",
    name: "Mysore Silk Teal Blue",
    category: "mysore-silk",
    price: 6799,
    compareAtPrice: 7599,
    description: "Teal blue Mysore silk with a delicate silver zari border and plain pallu.",
    fabric: "Pure Mysore Silk",
    color: "Teal Blue",
    stock: 9,
    createdAt: "2026-01-15T10:00:00.000Z",
  },
  {
    id: "p-012",
    slug: "mysore-silk-blush-pink",
    name: "Mysore Silk Blush Pink",
    category: "mysore-silk",
    price: 7099,
    compareAtPrice: null,
    description: "Soft blush pink Mysore silk with a fine gold border, understated and elegant.",
    fabric: "Pure Mysore Silk",
    color: "Blush Pink",
    stock: 6,
    createdAt: "2026-01-16T10:00:00.000Z",
  },
  {
    id: "p-013",
    slug: "handloom-cotton-indigo-check",
    name: "Handloom Cotton Indigo Check",
    category: "cotton-sarees",
    price: 1899,
    compareAtPrice: 2299,
    description: "Everyday indigo checked handloom cotton saree, soft and breathable.",
    fabric: "Handloom Cotton",
    color: "Indigo",
    stock: 12,
    featured: true,
    createdAt: "2026-01-17T10:00:00.000Z",
  },
  {
    id: "p-014",
    slug: "handloom-cotton-white-red-border",
    name: "Handloom Cotton White & Red Border",
    category: "cotton-sarees",
    price: 1699,
    compareAtPrice: null,
    description: "Crisp white handloom cotton with a classic red temple border.",
    fabric: "Handloom Cotton",
    color: "White & Red",
    stock: 15,
    createdAt: "2026-01-18T10:00:00.000Z",
  },
  {
    id: "p-015",
    slug: "handloom-cotton-mustard-stripe",
    name: "Handloom Cotton Mustard Stripe",
    category: "cotton-sarees",
    price: 1799,
    compareAtPrice: 1999,
    description: "Mustard striped handloom cotton saree, light and easy for daily wear.",
    fabric: "Handloom Cotton",
    color: "Mustard",
    stock: 10,
    createdAt: "2026-01-19T10:00:00.000Z",
  },
  {
    id: "p-016",
    slug: "handloom-cotton-olive-green",
    name: "Handloom Cotton Olive Green",
    category: "cotton-sarees",
    price: 1899,
    compareAtPrice: null,
    description: "Olive green handloom cotton with a thin black border, minimal and versatile.",
    fabric: "Handloom Cotton",
    color: "Olive Green",
    stock: 11,
    createdAt: "2026-01-20T10:00:00.000Z",
  },
  {
    id: "p-017",
    slug: "georgette-dusty-rose",
    name: "Georgette Dusty Rose",
    category: "chiffon-georgette",
    price: 3499,
    compareAtPrice: 3999,
    description: "Dusty rose georgette saree with delicate sequin work, light for evening wear.",
    fabric: "Georgette",
    color: "Dusty Rose",
    stock: 8,
    featured: true,
    createdAt: "2026-01-21T10:00:00.000Z",
  },
  {
    id: "p-018",
    slug: "chiffon-midnight-black",
    name: "Chiffon Midnight Black",
    category: "chiffon-georgette",
    price: 3299,
    compareAtPrice: null,
    description: "Midnight black chiffon saree with a subtle silver border, flowy drape.",
    fabric: "Chiffon",
    color: "Midnight Black",
    stock: 7,
    createdAt: "2026-01-22T10:00:00.000Z",
  },
  {
    id: "p-019",
    slug: "georgette-lavender-floral",
    name: "Georgette Lavender Floral",
    category: "chiffon-georgette",
    price: 3599,
    compareAtPrice: 3999,
    description: "Lavender georgette with a printed floral pattern and lace border.",
    fabric: "Georgette",
    color: "Lavender",
    stock: 6,
    createdAt: "2026-01-23T10:00:00.000Z",
  },
  {
    id: "p-020",
    slug: "chiffon-sea-green",
    name: "Chiffon Sea Green",
    category: "chiffon-georgette",
    price: 3199,
    compareAtPrice: null,
    description: "Sea green chiffon saree, plain body with a sequinned border.",
    fabric: "Chiffon",
    color: "Sea Green",
    stock: 9,
    createdAt: "2026-01-24T10:00:00.000Z",
  },
  {
    id: "p-021",
    slug: "bridal-red-kanjivaram",
    name: "Bridal Red Kanjivaram",
    category: "bridal-collection",
    price: 24999,
    compareAtPrice: 28999,
    description:
      "Heavy bridal red Kanjivaram silk with dense gold zari work covering the body and pallu.",
    fabric: "Pure Mulberry Silk",
    color: "Bridal Red",
    stock: 2,
    featured: true,
    createdAt: "2026-01-25T10:00:00.000Z",
  },
  {
    id: "p-022",
    slug: "bridal-maroon-gold-banarasi",
    name: "Bridal Maroon & Gold Banarasi",
    category: "bridal-collection",
    price: 21999,
    compareAtPrice: null,
    description: "Maroon and gold heavy Banarasi bridal saree with a richly worked pallu.",
    fabric: "Banarasi Katan Silk",
    color: "Maroon & Gold",
    stock: 3,
    createdAt: "2026-01-26T10:00:00.000Z",
  },
  {
    id: "p-023",
    slug: "bridal-champagne-gold",
    name: "Bridal Champagne Gold",
    category: "bridal-collection",
    price: 23499,
    compareAtPrice: 26999,
    description: "Champagne gold bridal silk saree with fine zari and stone work border.",
    fabric: "Pure Silk",
    color: "Champagne Gold",
    stock: 2,
    createdAt: "2026-01-27T10:00:00.000Z",
  },
  {
    id: "p-024",
    slug: "bridal-deep-magenta",
    name: "Bridal Deep Magenta",
    category: "bridal-collection",
    price: 22999,
    compareAtPrice: null,
    description: "Deep magenta bridal silk saree with a heavily embroidered gold pallu.",
    fabric: "Pure Silk",
    color: "Deep Magenta",
    stock: 3,
    createdAt: "2026-01-28T10:00:00.000Z",
  },
];
